# Generated by Django 4.2.16 on 2024-09-30 17:19

import Sinin_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sinin_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='photo',
            field=models.ImageField(default='photos/default/defaultimage.png', upload_to=Sinin_login.models.user_directory_path),
        ),
    ]
