# Generated by Django 4.2.16 on 2024-10-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sinin_login', '0003_remove_newuser_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(default='address', max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(default='first_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(default='last_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(default='phone', max_length=13),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='state',
            field=models.CharField(default='state', max_length=50),
        ),
    ]
