# Generated by Django 4.2.16 on 2024-10-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sinin_login', '0004_alter_newuser_address_alter_newuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='test/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sinin_login.newuser')),
            ],
        ),
    ]
